version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-tram-examples-java-spring-todo-list
    steps:
      - checkout
      - restore_cache:
          keys:
            - eventuate-tram-examples-java-spring-todo-list-{{ checksum "multi-module/build.gradle" }}
            - eventuate-tram-examples-java-spring-todo-list-
      - run:
          command: |
            export TERM=dumb
            cd single-module
            ./gradlew testClasses
            cd ../multi-module
            ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-tram-examples-java-spring-todo-list-{{ checksum "multi-module/build.gradle" }}
      - run:
          command: |
            export TERM=dumb
            ./.circleci/stop-and-remove-all-docker-containers.sh
      - run:
          command: |
            export TERM=dumb
            cd single-module
            ./build-and-test-all-mysql.sh
      - run:
          command: |
            export TERM=dumb
            cd single-module
            ./build-and-test-all-postgres.sh
      - run:
          command: |
            export TERM=dumb
            cd multi-module
            ./build-and-test-all-mysql.sh
      - run:
          command: |
            export TERM=dumb
            cd multi-module
            ./build-and-test-all-postgres.sh
      - run:
          name: Print container logs
          command: ./.circleci/print-container-logs.sh
          when: always
      - run:
          name: Save container logs
          command: ./.circleci/save-containers-and-tests.sh
          when: always
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
